import CancelImage from "./cancel.png";
import Background from "./hello.jpg"
import Shirt from "./shirt2.jpg"
import VisaImage from "./Visa-Logo-Free-Download-PNG.png"
import MasterCardImage from "./MasterCard_logo.png"
import PayPalImage from "./paypal-logo-png-512.png"
import ApplePayImage from "./apple-pay-card5428.jpg"
import ArrowRightImage from "./arrow-right-50.png"
import StarImage from "./star-48.png"
import ArrowDownImage from "./arrow-down-32.png"
import EmailImage from "./email-48.png"
import ArrowUpImage from "./arrow-up-50.png"
import ContactUsImage from "./contactuss.jpg"
import CrossImage from "./cross-50.png"
import AboutUsImage from "./aboutus.jpg"
import AboutUsProfile1 from "./aboutus1.png"
import AboutUsProfile2 from "./aboutus2.png"
import DhakalImage from "./dhakal.jpg"
import RajuImage from "./raju.jpg"
import GuddiImage from "./guddi.jpg"
export {DhakalImage,RajuImage,GuddiImage, AboutUsProfile1,AboutUsProfile2,AboutUsImage,CrossImage,ContactUsImage,ArrowUpImage,EmailImage,CancelImage, Background,Shirt,VisaImage,MasterCardImage,PayPalImage,ApplePayImage,ArrowRightImage,StarImage,ArrowDownImage };

