import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/static/NavBar";
import MobileNavBar from "@/components/static/MobileNavBar";
import StoreProvider from "./StoreProvider";
import Footer from "@/components/static/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <div>
            <NavBar />
            <MobileNavBar />
            {children}
            <Footer/>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
